
server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: CONFIG-PROD
          uri: lb://CONFIG-PROD
          predicates:
            - Path=/usuarios/**,/segundoControlador/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hoteles/**

        - id: CONFIG-DEV
          uri: lb://CONFIG-DEV
          predicates:
            - Path=/calificaciones/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka