server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/segundoMicro
    username : postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka