server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservicios


  config:
    import: configserver:http://localhost:8085
  profiles:
    active: dev