server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_primer_proyecto
    username: root
    password:
    driver: com.mysql.cj.jdbc.Driber

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
