server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_primer_proyecto
    username: root
    password: cuenca
    driver: com.mysql.cj.jdbc.Driber

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  config:
    import: configserver:http://localhost:8085
  profiles:
    active: prod



management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always



resilience4j:
  circuit-braker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimunNUmberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED