server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_primer_proyecto
    username: user_name
    password: password
    driver: com.mysql.cj.jdbc.Driber

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  config:
    import: configserver:http://localhost:8085
  profiles:
    active: prod
